feat: add feature client for izanami
ovhlabs/izanami-go-client pull request #1
Opened 2018-03-19 13:46 UTC by sguiheux

2018-03-19 13:56 UTC, fsamin requested changes

2018-03-19 13:56 UTC, fsamin commented on client.go
> +type client struct {
should be public 
or make a interface and only return it

2018-03-19 13:56 UTC, fsamin commented on client.go
> +func New(host, clientID, secret string) *client {
is it possible to ping the izanami and raise an error if not available, or auth failed ?

2018-03-19 13:56 UTC, fsamin commented on client.go
> +func (c *client) Feature() *featureClient {
should return a public interface

2018-03-19 13:56 UTC, fsamin commented on client.go
> +package izanami_client
package should not contains underscore

2018-03-19 13:56 UTC, fsamin commented on feature.go
> +func (c *featureClient) listAll() ([]FeatureModel, error) {
should be public ?

2018-03-19 13:56 UTC, fsamin commented on feature.go
> +func (c *featureClient) create(feat FeatureModel) error {
should be public ?

2018-03-19 14:04 UTC, sguiheux commented on feature.go
> +func (c *featureClient) create(feat FeatureModel) error {
done

2018-03-19 14:04 UTC, sguiheux commented on feature.go
> +func (c *featureClient) listAll() ([]FeatureModel, error) {
done

2018-03-19 14:04 UTC, sguiheux commented on client.go
> +package izanami_client
done

2018-03-19 14:12 UTC, fsamin requested changes

2018-03-19 14:12 UTC, fsamin commented on http.go
> +	httpClient = &http.Client{
should be a public attribute of the client

2018-03-19 14:12 UTC, fsamin commented on README.md
> +features, errF := c.Feature().listAll()
update the doc

2018-03-19 14:13 UTC, fsamin commented
we should wrote a very few tests, to able able to check if the server new versions doesn't have impact on this code

2018-03-19 14:34 UTC, bnjjj requested changes

2018-03-19 14:34 UTC, bnjjj commented on README.md
> +```
add go

2018-03-20 08:43 UTC, fsamin approved these changes

2018-03-20 08:55 UTC, bnjjj approved these changes

2018-03-20 08:57 UTC, yesnault approved these changes

2018-03-20 08:58 UTC, merged